# Generated by Django 6.0.2 on 2026-02-27 13:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('ACCOUNTS', 'Accounts'), ('MEMBERS', 'Members'), ('SAVINGS', 'Savings'), ('LOANS', 'Loans'), ('FINANCE', 'Finance'), ('REPORTS', 'Reports'), ('SETTINGS', 'Settings'), ('SYSTEM', 'System'), ('SECURITY', 'Security')], max_length=30)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('POST', 'Post'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('VIEW', 'View'), ('EXPORT', 'Export')], max_length=30)),
                ('message', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='members.member')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['module', 'action'], name='audits_audi_module_599a40_idx'), models.Index(fields=['created_at'], name='audits_audi_created_61fc5f_idx'), models.Index(fields=['reference'], name='audits_audi_referen_13e08e_idx')],
            },
        ),
    ]
