# Generated by Django 4.2 on 2026-03-04 13:16

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('term_months', models.PositiveIntegerField(default=12)),
                ('interest_rate_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('interest_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('fees_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('penalties_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_payable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLEARED', 'Cleared'), ('DEFAULTED', 'Defaulted'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('disbursement_status', models.CharField(choices=[('PENDING', 'Pending'), ('AUTHORIZED', 'Authorized'), ('DISBURSED', 'Disbursed')], default='PENDING', max_length=20)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('disbursement_reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('interest_rate_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('min_term_months', models.PositiveIntegerField(default=1)),
                ('max_term_months', models.PositiveIntegerField(default=36)),
                ('min_savings_required', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('max_multiplier_of_savings', models.DecimalField(decimal_places=2, default=Decimal('3.00'), help_text='Max loan = savings * this multiplier', max_digits=6)),
                ('processing_fee_flat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('processing_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage of principal', max_digits=6)),
                ('late_fee_flat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('late_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage of overdue amount', max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('principal_component', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('interest_component', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('penalty_component', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('channel', models.CharField(choices=[('MEMBER', 'Member'), ('STAFF', 'Staff')], default='STAFF', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('POSTED', 'Posted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, editable=False, max_length=30, unique=True)),
                ('narration', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_repayments_created', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='loans.loan')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_repayments_posted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('term_months', models.PositiveIntegerField(default=12)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.CharField(blank=True, max_length=255)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loan_apps', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to='members.member')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='loans.loanproduct')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_loan_apps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan', to='loans.loanapplication'),
        ),
        migrations.AddField(
            model_name='loan',
            name='authorized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='members.member'),
        ),
        migrations.AddField(
            model_name='loan',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='loans.loanproduct'),
        ),
    ]
