# Generated by Django 4.2 on 2026-03-04 13:16

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('withdrawal_fee_flat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('withdrawal_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('deposit_fee_flat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('deposit_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Charge Policy',
            },
        ),
        migrations.CreateModel(
            name='SavingsProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('minimum_monthly_contribution', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('allow_withdrawals', models.BooleanField(default=True)),
                ('interest_rate_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
