# Generated by Django 6.0.2 on 2026-02-27 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_number', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('EXITED', 'Exited')], default='ACTIVE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('national_id', models.CharField(max_length=20, unique=True)),
                ('kra_pin', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('town', models.CharField(blank=True, max_length=120)),
                ('county', models.CharField(blank=True, max_length=120)),
                ('alternative_phone', models.CharField(blank=True, max_length=15)),
                ('next_of_kin_name', models.CharField(blank=True, max_length=120)),
                ('next_of_kin_phone', models.CharField(blank=True, max_length=15)),
                ('next_of_kin_relationship', models.CharField(blank=True, max_length=60)),
                ('membership_fee_paid', models.BooleanField(default=False)),
                ('membership_fee_paid_at', models.DateTimeField(blank=True, null=True)),
                ('account_fee_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_account_fee_charged_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
